### ISSUE TITLE
On Android, Out of memory error when adding big files (31mb) and sending as base64 string

### ISSUE THREAD

**Issue by heromanofe** [ascheja/xml-rpc-kt#2]
I am using Xiaomi 2201116PG Android 11, API 30 and I was crashing with:

2023-01-28 22:35:38.179 22752-25643 ationtestxmlrp          com.example.myapplicationtestxmlrpc  W  Throwing OutOfMemoryError "Failed to allocate a 49441448 byte allocation with 15791448 free bytes and 15MB until OOM, target footprint 268435456, growth limit 268435456" (VmSize 5559272 kB)
2023-01-28 22:35:38.184 22752-25643 AndroidRuntime          com.example.myapplicationtestxmlrpc  E  FATAL EXCEPTION: DefaultDispatcher-worker-10
                                                                                                    Process: com.example.myapplicationtestxmlrpc, PID: 22752
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 49441448 byte allocation with 15791448 free bytes and 15MB until OOM, target footprint 268435456, growth limit 268435456
                                                                                                    	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
                                                                                                    	at java.lang.StringBuffer.toString(StringBuffer.java:671)
                                                                                                    	at org.apache.harmony.xml.dom.CharacterDataImpl.getData(CharacterDataImpl.java:51)
                                                                                                    	at org.apache.xml.serializer.TreeWalker.dispatachChars(TreeWalker.java:245)
                                                                                                    	at org.apache.xml.serializer.TreeWalker.startNode(TreeWalker.java:416)
                                                                                                    	at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:145)
                                                                                                    	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390)
                                                                                                    	at org.ascheja.xmlrpc.protocol.UtilKt.writeToByteArray(Util.kt:36)
                                                                                                    	at org.ascheja.xmlrpc.protocol.UtilKt.writeToByteArray$default(Util.kt:32)
                                                                                                    	at org.ascheja.xmlrpc.ktor.client.LibraryKt.xmlRpc(Library.kt:28)
                                                                                                    	at com.example.myapplicationtestxmlrpc.MainActivity.mailAttach(MainActivity.kt:157)
                                                                                                    	at com.example.myapplicationtestxmlrpc.MainActivity$mailAttach$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e35f7c4, Dispatchers.Default]
2023-01-28 22:35:38.186 22752-25643 OOMEventManagerFK       com.example.myapplicationtestxmlrpc  D  checkEventAndDumpForJE: 0

Until I added into manifest:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    ...
    <application
        android:largeHeap="true"
        ...

**Comment by heromanofe** [comment]
struct value is
val str = StructValue(mapOf(
                        "description" to StringValue("hhh"),
                        "name" to StringValue(datasUse.filename),
                        "type" to StringValue("binary"),
                        "datas" to StringValue(datasUse.data)
                    )
                    )
data is taken from 

like this

intent;;;
      var intent = Intent(Intent.ACTION_GET_CONTENT)
        intent.type = "text/*"
        intent.addCategory(Intent.CATEGORY_OPENABLE)
        intent = Intent.createChooser(intent, "Choose a file")
        intentActivityWResult.launch(intent)
result;
val data: Uri = result.data?.data ?: return@launch
....
 var stream: InputStream? = contentResolver.openInputStream(data)
 val bytes: ByteArray = IOUtils.toByteArray(stream) <--     implementation 'commons-io:commons-io:2.11.0'
 val encoded = bytes.encodeBase64() <--  Gradle: io.ktor:ktor-utils-jvm:2.0.3 (ktor-utils-jvm-2.0.3.jar)

**Comment by ascheja** [comment]
I've pushed out a new release that might help you by streaming the client body instead of putting it all into one `ByteArray` first, but In general you will have to look for other ways of optimizing your code if you want to run with the lower memory limit.

**Comment by heromanofe** [comment]
Yea, I was able to fix by adding large hip into manifest before, will see if this streaming thing works.

**Comment by heromanofe** [comment]
this wasn't pushed to gradle so I will need to implement it manually
